version: '3.5'
services:
    app:
        build:
            context: ./backend
            dockerfile: app.dockerfile
        working_dir: /var/www
        container_name: api-php
        volumes:
          - ./backend:/var/www
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=database"
        networks:
          - db-net

    web:
        build:
            context: ./backend
            dockerfile: web.dockerfile
        working_dir: /var/www
        container_name: api-web
        volumes:
          - app
        ports:
          - 8888:8888
        networks:
          - db-net

    mongo:
      image: "mongo:3-stretch"
      container_name: mongodb-api
      ports:
        - "27017:27017"
      networks:
        - db-net

    mongo-express:
      image: "mongo-express:latest"
      container_name: mongo-express-api
      ports:
        - "8081:8081"
      networks:
        - db-net

    database:
      image: mariadb:10.3
      container_name: api-database
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - "MYSQL_DATABASE=appdb"
        - "MYSQL_USER=admin"
        - "MYSQL_PASSWORD=123"
        - "MYSQL_ROOT_PASSWORD=123"
      ports:
        - "3306:3306"
      networks:
        - db-net

networks:
  db-net:
    external:
      name: db_network
