version: '3.5'
services:
    mongo:
      image: "mongo:3-stretch"
      container_name: mongodb-api
      ports:
        - "27017:27017"
      networks:
        - proxynet

    mongo-express:
      image: "mongo-express:latest"
      container_name: mongo-express-api
      ports:
        - "8081:8081"
      networks:
        - proxynet

networks:
  proxynet:
    name: db_network
